### ISSUE TITLE
unparse with comments: source_range: undefined method location

### ISSUE THREAD

**Issue by neil-ongkingco-apollo** [mbj/unparser#344]
Getting this error when trying out unparser with comments:
```
/Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser/comments.rb:108:in `source_range': undefined method `location' for [s(:lvasgn, :x, (NoMethodError)
  s(:send,
    s(:lvar, :x), :+,
    s(:int, 1))), [#<Parser::Source::Comment (string):2:1 "# This is a comment">]]:Array
	from /Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser/comments.rb:19:in `source_range'
	from /Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser/comments.rb:82:in `take_before'
	from /Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser/generation.rb:70:in `emit_comments_before'
	from /Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser/generation.rb:45:in `with_comments'
	from /Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser/generation.rb:15:in `write_to_buffer'
	from /Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser.rb:68:in `block in unparse'
	from <internal:kernel>:90:in `tap'
	from /Users/neilongkingco/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/unparser-0.6.7/lib/unparser.rb:63:in `unparse'
	from /Users/neilongkingco/src/ruby/parser/parser_test.rb:17:in `<main>'
```

RUBY_VERSION 3.0.1

Gem versions:
```    ast (2.4.2)
    diff-lcs (1.5.0)
    parser (3.2.2.1)
      ast (~> 2.4.1)
    unparser (0.6.7)
      diff-lcs (~> 1.3)
      parser (>= 3.2.0)
```

Source:

```# frozen_string_literal: true

require 'parser'
require 'parser/current'
require 'unparser'

puts "Parser"
ast = Unparser.parse_with_comments(
"
# This is a comment
x = x + 1
")
puts ast

puts "Unparser"
#has problems with parse_with_comments
puts Unparser.unparse(ast)
```

**Comment by mbj** [comment]
@neil-ongkingco-apollo thanks for the report.

I have got very limited time for OSS work, outside of the features I need. Comment reproduction is not a feature I need currently. So I'd be very happy you could try to do a patch here.

Otherwise be prepared this will take a while.

**Comment by neil-ongkingco-apollo** [comment]
Found the problem, I wasn't passing the comments on. Fixed it by doing this:

```
ast, comments = Unparser.parse_with_comments
...
Unparser.unparse(ast, comments)
```

**Comment by neil-ongkingco-apollo** [comment]
Planning to do some rewriting of jbuilders to plain ruby. I think unparser will make that a lot easier.

**Comment by mbj** [comment]
k, thx.
