### ISSUE TITLE
Can't unparse AST tree composed with AST::Sexp manually

### ISSUE THREAD

**Issue by dredozubov** [mbj/unparser#39]
unparser relies upon location attribute on AST nodes, which is very weird. It can be demonstrated with a simple code like this:
```ruby
require 'unparser'

include AST::Sexp

literal_ast = s(:def,
                :foo,
                s(:args,
                  s(:arg,
                     :x)),
                s(:send, s(:lvar, :x), :+, s(:int, 3)))

meth = <<EOM
def foo(x)
  x + 3
end
EOM

parsed_ast = Parser::CurrentRuby.parse(meth)
p '='*10
p literal_ast
p '='*10
p parsed_ast
p '='*10
p literal_ast == parsed_ast # prints 'true'
p literal_ast.to_sexp == parsed_ast.to_sexp # prints 'true'
p '='*10
Unparser.unparse(parsed_ast) # succeeds without an issue
p "unparsed from parsed ast"
Unparser.unparse(literal_ast) # BOOM!!!
p "unparsed from literal ast" # nope, it broke on previous line
```

unparser (0.2.2) and ast (2.0.0)

it fails with:
```
/Users/dr/.gem/ruby/2.2.0/gems/unparser-0.2.2/lib/unparser/comments.rb:105:in `source_range': undefined method `location' for #<AST::Node:0x007fb084d4a508> (NoMethodError)
	from /Users/dr/.gem/ruby/2.2.0/gems/unparser-0.2.2/lib/unparser/comments.rb:19:in `source_range'
	from /Users/dr/.gem/ruby/2.2.0/gems/unparser-0.2.2/lib/unparser/comments.rb:81:in `take_before'
	from /Users/dr/.gem/ruby/2.2.0/gems/unparser-0.2.2/lib/unparser/emitter.rb:321:in `emit_comments_before'
	from /Users/dr/.gem/ruby/2.2.0/gems/unparser-0.2.2/lib/unparser/emitter.rb:102:in `write_to_buffer'
	from /Users/dr/.gem/ruby/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /Users/dr/.gem/ruby/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /Users/dr/.gem/ruby/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /Users/dr/.gem/ruby/2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/dr/.gem/ruby/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /Users/dr/.rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/dr/.gem/ruby/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /Users/dr/.gem/ruby/2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /Users/dr/.gem/ruby/2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /Users/dr/.gem/ruby/2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /Users/dr/.gem/ruby/2.2.0/gems/unparser-0.2.2/lib/unparser.rb:31:in `unparse'
	from unparser_fail.rb:30:in `<main>'
```

**Comment by dredozubov** [comment]
I believe it would be beneficial if a module like this would be exported by `unparser/manual` or something similar https://github.com/mbj/unparser/commit/cd7bb3b0df92b806f905a1e69e75b1f558b92ec3#diff-04c6e90faac2675aa89e2176d2eec7d8R37

**Comment by mbj** [comment]
I do not think that unparser should export such a module. It would be better owned by the [parser](https://github.com/whitequark/parser) gem.

**Comment by dredozubov** [comment]
Yeah, you're right, i've had a brain-freeze or something. For some reason i've decided that `#s` is a method of unparser, while writing comment above. Not an unparser issue.

**Comment by mbj** [comment]
@dredozubov I think you can open an issue at the parser gem, IMO its likely it can be addressed easily.
